build production dockerfile

diff --git a/next/Dockerfile.prod b/next/Dockerfile.prod
--- a/next/Dockerfile.prod
+++ b/next/Dockerfile.prod
@@ -1,40 +1,70 @@
-# # Install dependencies only when needed
-# FROM node:lts-alpine AS deps
+# syntax=docker.io/docker/dockerfile:1
 
-# WORKDIR /opt/app
-# COPY package.json yarn.lock ./
-# RUN yarn install --frozen-lockfile
+FROM node:18-alpine AS base
 
-# # Rebuild the source code only when needed
-# # This is where because may be the case that you would try
-# # to build the app based on some `X_TAG` in my case (Git commit hash)
-# # but the code hasn't changed.
-# FROM node:lts-alpine AS builder
-
-# ENV NODE_ENV=production
-# WORKDIR /opt/app
-
-# COPY . .
-# COPY --from=deps /opt/app/node_modules ./node_modules
-# RUN yarn build
-
-# # Production image, copy all the files and run next
-# FROM node:lts-alpine AS runner
-
-# ARG X_TAG
-# WORKDIR /opt/app
-# ENV NODE_ENV=production
-# COPY --from=builder /opt/app/next.config.js ./
-# COPY --from=builder /opt/app/public ./public
-# COPY --from=builder /opt/app/.next ./.next
-# COPY --from=builder /opt/app/node_modules ./node_modules
-# ENV NEXT_TELEMETRY_DISABLED 1
-# CMD ["node", ".next/standalone/server.js"]
-
-FROM node:latest
+# Install dependencies only when needed
+FROM base AS deps
+# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
+RUN apk add --no-cache libc6-compat
 WORKDIR /app
+
+# Install dependencies based on the preferred package manager
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc* ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+
+# Rebuild the source code only when needed
+FROM base AS builder
+WORKDIR /app
+COPY --from=deps /app/node_modules ./node_modules
 COPY . .
-RUN npm install
-RUN npm run build
+
+# Next.js collects completely anonymous telemetry data about general usage.
+# Learn more here: https://nextjs.org/telemetry
+# Uncomment the following line in case you want to disable telemetry during the build.
+# ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN \
+  if [ -f yarn.lock ]; then yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then corepack enable pnpm && pnpm run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+# Production image, copy all the files and run next
+FROM base AS runner
+WORKDIR /app
+
+ENV NODE_ENV=production
+# Uncomment the following line in case you want to disable telemetry during runtime.
+# ENV NEXT_TELEMETRY_DISABLED=1
+
+RUN addgroup --system --gid 1001 nodejs
+RUN adduser --system --uid 1001 nextjs
+
+COPY --from=builder /app/public ./public
+
+# Set the correct permission for prerender cache
+RUN mkdir .next
+RUN chown nextjs:nodejs .next
+
+# Automatically leverage output traces to reduce image size
+# https://nextjs.org/docs/advanced-features/output-file-tracing
+COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
+COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
+
+USER nextjs
+
 EXPOSE 3000
-CMD ["npm", "run", "start"]
+
+ENV PORT=3000
+
+# server.js is created by next build from the standalone output
+# https://nextjs.org/docs/pages/api-reference/next-config-js/output
+ENV HOSTNAME="0.0.0.0"
+CMD ["node", "server.js"]
